change set_num_replicas in docker_container_manager (#616)
* change set_num_replicas in docker_container_manager, due to - AttributeError: 'NoneType' object has no attribute 'get'

* revise set_num_replicas logic

* changed 'container' to 'inspect_container'